name       : poco
version    : 1.12.2
release    : 3
source     :
    - https://github.com/pocoproject/poco/archive/refs/tags/poco-1.12.2-release.tar.gz : 30442ccb097a0074133f699213a59d6f8c77db5b2c98a7c1ad9c5eeb3a2b06f3
license    : BSL-1.0
component  :
    - programming.library
    - tools: programming.tools
summary    : C++ libraries for building network- and internet-based applications
description: |
    The POCO C++ Libraries are powerful cross-platform C++ libraries for building network- and internet-based applications that run on desktop, server, mobile, IoT, and embedded systems.
patterns   :
    - tools: /usr/bin/*
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Rename arc to avoid a conflict with arcanist
    mv $installdir/usr/bin/arc $installdir/usr/bin/poco-arc
