name       : poco
version    : 1.11.1
release    : 1
source     :
    - https://github.com/pocoproject/poco/archive/refs/tags/poco-1.11.1-release.tar.gz : 2412a5819a239ff2ee58f81033bcc39c40460d7a8b330013a687c8c0bd2b4ac0
license    : BSL-1.0
component  : programming.library
summary    : C++ libraries for building network- and internet-based applications
description: |
    The POCO C++ Libraries are powerful cross-platform C++ libraries for building network- and internet-based applications that run on desktop, server, mobile, IoT, and embedded systems.
patterns   :
    - tools: /usr/bin/*
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Rename arc to avoid a conflict with arcanist
    mv $installdir/usr/bin/arc $installdir/usr/bin/poco-arc
