name       : poco
version    : 1.12.4
release    : 5
source     :
    - https://github.com/pocoproject/poco/archive/refs/tags/poco-1.12.4-release.tar.gz : 71ef96c35fced367d6da74da294510ad2c912563f12cd716ab02b6ed10a733ef
license    : BSL-1.0
component  :
    - programming.library
    - tools : programming.tools
summary    : C++ libraries for building network- and internet-based applications
description: |
    The POCO C++ Libraries are powerful cross-platform C++ libraries for building network- and internet-based applications that run on desktop, server, mobile, IoT, and embedded systems.
builddeps  :
    - pkgconfig(expat)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
patterns   :
    - tools : /usr/bin/*
setup      : |
    %cmake_ninja \
      -D POCO_UNBUNDLED=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Rename arc to avoid a conflict with arcanist
    mv $installdir/usr/bin/arc $installdir/usr/bin/poco-arc
